[shows]
    [shows.show-5]
        title = "Composer Project Ahrens & Flaherty"
        character = "Self"
        company = "CAP21 / Molloy Univ."
        director = "Aimée Francis"
    [shows.show-4]
        title = "Bridgetown Cabaret 2020"
        character = "Self"
        company = "Bridgetown Conservatory"
        director = "Rick Lewis"
