[shows]
[shows.samantha]
title = "Samantha Single Handed"
character = "Shelley"
company = "First Table Read"
director = "Aaron Gandy"
[shows.christmas]
title = "Christmas Cabaret"
character = "Self"
company = "Bridgetown Conservatory"
director = "Marcus Harbaugh"
# [shows.alumni]
#     title = "Alumni Cabaret"
#     character = "Self"
#     company = "Bridgetown Conservatory"
#     director = "Marcus Harbaugh"
[shows.songdance]
title = "Song & Dance Revue"
character = "Self"
company = "CAP21 / Molloy Univ."
director = "Lori Leshner"
[shows.composer]
title = "Composer Project Revue"
character = "Self"
company = "CAP21 / Molloy Univ."
director = "Aimée Francis"
[shows.bridgetown]
title = "Bridgetown Cabaret 2020"
character = "Self"
company = "Bridgetown Conservatory"
director = "Rick Lewis"
