[shows]
    [shows.show-7]
        title = "Kiss Me Kate"
        character = "Gangster #2"
        company = "Madison Theatre"
        director = "Angelo Fraboni"
    [shows.show-6]
        title = "Legally Blonde"
        character = "Dewey / Aaron"
        company = "Madison Theatre"
        director = "Angelo Fraboni"
    [shows.show-5]
        title = "In Pieces"
        character = "Grey"
        company = "Bridgetown Conservatory"
        director = "Kevin Paul Clark"
    [shows.show-1]
        title = "Theory of Relativity"
        character = "Ryan"
        company = "Bridgetown Conservatory"
        director = "Rick Lewis"
    [shows.show-2]
        title = "A Midsummer Night's Dream"
        character = "Oberon"
        company = "NW Children's Theatre"
        director = "Sarah Jane Hardy"
    [shows.show-3]
        title = "Matilda"
        character = "Sergei/Ensemble"
        company = "NW Children's Theatre"
        director = "Sarah Jane Hardy"
    [shows.show-4]
        title = "Bridgetown Cabaret 2020"
        character = "Self"
        company = "Bridgetown Conservatory"
        director = "Rick Lewis"
