#:schema https://raw.githubusercontent.com/mintyfrankie/brilliant-CV/main/metadata.toml.schema.json

# Set the output language
# INFO: value must matches folder suffix; i.e "zh" -> "./modules_zh"
language = "en"

[songs]
    [songs.goldenage]
        [songs.goldenage.allthethings]
            title = "All The Things You Are"
            source = "Very Warm for May"
            composer = "Hammerstein & Kern"
            type = "Ballad"
            time = "1:15"
            bars = "32"
        [songs.goldenage.singa]
            title = "I Love to Sing-a"
            source = "The Singing Kid"
            composer = "Arlen & Yip"
            type = "Uptempo"
            time = "1:15"
            bars = "32, 16"
        [songs.goldenage.kick]
            title = "Ain't That a Kick in the Head"
            source = "Dean Martin"
            composer = "Van Heusen & Cahn"
            type = "Uptempo"
            time = "1:15"
            bars = "32"
    [songs.contemporary]
        [songs.contemporary.magicfoot]
            title = "Magic Foot"
            source = "25th Annual"
            composer = "William Finn"
            type = "Uptempo"
            time = "1:15"
            bars = "32"
    [songs.speciality]
        [songs.speciality.brightside]
            title = "Bright Side of Life"
            source = "Life of Brian"
            composer = "Eric Idle"
            type = "Uptempo"
            time = "1:15"
            bars = "32"

[layout]
    # Optional values: skyblue, red, nephritis, concrete, darknight
    # You can also use a custom color by hex code i.e. "#1E90FF"
    awesome_color = "concrete"

    # Skips are for controlling the spacing between sections and entries
    before_section_skip = "7pt"
    before_entry_skip = "1pt"
    before_entry_description_skip = "1pt"

    [layout.fonts]
        regular_fonts = ["EB Garamond", "Source Sans 3"]
        header_font = "EB Garamond"

    [layout.header]
        # Optional values: left, center, right
        header_align = "left"

        # Decide if you want to display profile photo or not
        display_profile_photo = false

    [layout.entry]
        # Decide if you want to put your company in bold or your position in bold
        display_entry_society_first = true

        # Decide if you want to display organisation logo or not
        display_logo = true

[inject]
    # Decide if you want to inject AI prompt or not
    inject_ai_prompt = false

    # Decide if you want to inject keywords or not
    inject_keywords = true
    injected_keywords_list = ["Data Analyst", "GCP", "Python", "SQL", "Tableau"]

# TODO: pull this information from normal metadata.toml so it'd not repeated
[personal]
    first_name = "Finn"
    last_name = "Rutis"

    pronouns = "they / them"
    # The order of this section will affect how the entries are displayed
    # The custom value is for any additional information you want to add, name it as custom-1, custom-2, etc.
    [personal.info]
        # github = "mintyfrankie"
        phone = "503-267-5052"
        email = "me@finnrut.is"
        # linkedin = "johndoe"
        # gitlab = "mintyfrankie"
        homepage = "www.finnrut.is"
        vocal-part = "Tenor"
        # extraInfo = "I am a cool kid"
        # height = "6'"
        # eyes = "Green"
        # hair = "Brown"

# add a new section if you want to include the language of your choice
# i.e. [[lang.ru]]
# each section must contains the following fields
[lang.en]
    header_quote = "Musical theatre performer & voiceover artist interested in shining light on unconscious parts of the human experience."
    cv_footer = "Rep Sheet"
    letter_footer = "Cover letter"

[lang.fr]
    header_quote = "Analyste de données expérimenté à la recherche d'un emploi à temps plein disponible dès maintenant"
    cv_footer = "Résumé"
    letter_footer = "Lettre de motivation"

[lang.zh]
    header_quote = "具有丰富经验的数据分析师，随时可入职"
    cv_footer = "简历"
    letter_footer = "申请信"

 # For languages that are not written in Latin script
 # Currently supported non-latin language codes: ("zh", "ja", "ko", "ru")
[lang.non_latin]
    name = "王道尔"
    font = "Heiti SC"
