baseURL = "https://finnrut.is"
languageCode = 'en-us'
theme = "hugo-resume"

[params]
    title = "finn's real website" 
    description = "i'm gonna build my website i swear"
    favicon = ""
    message = "how long until my birthday" 
    release = "October 26, 2025"
    background = "" 

socialIcons = [
    {name = "email", url = "example@example.com"},      
    {name = "twitter", url = "https://twitter.com/"},    
    {name = "facebook", url = "https://facebook.com/"},    
    {name = "github", url = "https://github.com/"},    
    {name = "instagram", url = "https://instagram.com/"},    
    {name = "tiktok", url = "https://tiktok.com/"},    
    {name = "linkedin", url = "https://linkedin.com/"},    
] 

[params.twitter]
	enable = false 
	username = "mansoorbarri"
