name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  check:
    name: flake checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: nixbuild/nix-quick-install-action@v34
      - name: Run nix flake check
        run: nix flake check --print-build-logs

  build:
    uses: ./.github/workflows/_build.yml
    with:
      deploy: false
