name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: build artifacts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v34
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      # - name: Build site
      #   run: |
      #     nix build .#packages.x86_64-linux.website -o ./result-website
      - name: Prepare pages artifact
        run: |
          mkdir -p ./pages
          # cp -R ./result-website/. ./pages/
      - name: Build resume
        run: |
          nix build .#packages.x86_64-linux.resume -o ./result-resume
      - name: Build work resume
        run: |
          nix build .#packages.x86_64-linux.work-resume -o ./result-work-resume
      - name: Add built files to pages artifact
        run: |
          shopt -s nullglob
          png_files=(./result-resume/CV_FinnRutis_*.png)
          if [ "${#png_files[@]}" -ne 1 ]; then
            echo "Expected exactly 1 resume PNG file, but found ${#png_files[@]}."
            exit 1
          fi
          cp "${png_files[0]}" ./pages/resume.png
          resume=(./result-resume/CV_FinnRutis_*.pdf)
          rep=(./result-resume/Rep-Sheet_FinnRutis_*.pdf)
          cp "${resume[0]}" ./pages/resume.pdf
          cp "${rep[0]}" ./pages/rep.pdf
          work_resume=(./result-work-resume/Work_CV_FinnRutis_*.pdf)
          cp "${work_resume[0]}" ./pages/work-resume.pdf
          work_png=(./result-work-resume/Work_CV_FinnRutis_*.png)
          cp "${work_png[0]}" ./pages/work-resume.png
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
